name: main

on:
  push:
    branches:
      - 'master'
    tags:
        - "*"
  pull_request:
    branches:
      - 'master'

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  tests:
    name: Unit Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        - 3.10-dev

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade tox tox-py

    - name: Run tox targets for ${{ matrix.python-version }}
      run: tox --py current

    - name: Upload code coverage
      if: matrix.python-version == '3.6'
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        flags: unittests

  integration-tests:
    name: Integration Tests (Python 3.6 ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
         - ubuntu-18.04
         - ubuntu-20.04
         - windows-latest
         - macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade tox

    - name: Run tox
      run: tox -e integration
