name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish distributions to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

    - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-publish-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-dev --no-interaction --no-root

    - name: Publish
        run: poetry publish --build --no-interaction -u __token__ -p ${{ secrets.PYPI_TOKEN }}
